# Generated by Django 4.1.3 on 2022-11-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('debtor', 'debtor'), ('creditor', 'creditor')], default='none', max_length=8),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11),
        ),
    ]
