# Generated by Django 4.1.3 on 2022-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_has_room_customuser_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
    ]
