# Generated by Django 4.1.3 on 2022-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
