# Generated by Django 4.1.3 on 2022-11-05 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_member_room_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='purchases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.purchase'),
        ),
    ]
