# Generated by Django 4.1.3 on 2022-11-05 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0005_remove_purchase_items_purchase_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='member',
        ),
        migrations.AddField(
            model_name='purchase',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='shared_purchase', to=settings.AUTH_USER_MODEL),
        ),
    ]
