# Generated by Django 4.1.3 on 2022-11-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_room_purchases_purchase_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Room name'),
        ),
    ]
