# Generated by Django 4.1.3 on 2022-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
