# Generated by Django 4.1.3 on 2022-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_item_in_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sum',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
