# Generated by Django 4.1.3 on 2022-11-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_item_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='rooms.room'),
        ),
    ]
