# Generated by Django 4.1.3 on 2022-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_room_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datetime_bought',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
