# Generated by Django 4.1.3 on 2022-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_item_datetime_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='datetime_bought',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
