# Generated by Django 4.1.3 on 2022-11-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
