# Generated by Django 4.1.3 on 2022-11-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='member_share',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaser_share',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
