# Generated by Django 4.1.3 on 2022-11-22 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0021_purchase_member_share_purchase_purchaser_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='member',
            field=models.ManyToManyField(related_name='shared_purchase', to=settings.AUTH_USER_MODEL),
        ),
    ]
