# Generated by Django 4.1.3 on 2022-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_purchase_adder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
